import Head from 'next/head';
// import { Inter } from 'next/font/google';
import Link from 'next/link';
import styles from '../../styles/Main.module.css';

// const inter = Inter({ subsets: ['latin'] });

const posts = [
  {
    id: 1,
    author: 'Nick',
    title: 'About cats',
    text: 'HAkkjkhbbxxx khjh nk kkkl l',
  },
  {
    id: 2,
    author: 'Kate',
    title: 'About dogs',
    text: 'Knfgfjghbbxxx khjh nk kkkl l',
  },
  {
    id: 3,
    author: 'Alina',
    title: 'About rabbits',
    text: 'Khhjnk mBHkml, kJJkll;vdv',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}> */}
      <main className={`${styles.main}`}>
        <h1>The Blog !</h1>
        <ul>
          {posts.map((post) => (
            <li key={post.id}>
              <Link
                href={{
                  // pathname: `/posts/${encodeURIComponent(post.id)}`,
                  pathname: `/posts/${post.id}`,
                  query: { id: post.id },
                }}
              >
                {post.title}
              </Link>
            </li>
          ))}
        </ul>
        <Link href="/">
          <button style={{ padding: '10px' }}>Go to The Main</button>
        </Link>
      </main>
    </>
  );
}
