import Head from 'next/head';
import Link from 'next/link';
import { createContext, useCallback, useMemo, useState } from 'react';

import RootLayout from './layout';
import styles from '../styles/Main.module.css';
import Announcement from '../components/Announcement';

export const ThemeContext = createContext('light');
// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [theme, setTheme] = useState('light');
  const [userLocation, setUserLocation] = useState('Georgia');
  const prices = [1, 2, 3, 4, 5, 6];

  const handleOnClick = useCallback(() => {
    console.log(`Special offer for ${userLocation}`);
  }, [userLocation]);

  
  function countBestPrice(prices: number[]): number {
    return Math.min(...prices);
  }
  const bestPrice = useMemo(() => countBestPrice(prices), [prices]);


  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeContext.Provider value={theme}>
        <RootLayout>
          <main className={styles.main}>
            <h1>Main page</h1>
            <Announcement bestPrice={bestPrice} onClick={handleOnClick} />
            <label>
              <input
                type="checkbox"
                checked={theme === 'dark'}
                onChange={(e) => {
                  setTheme(e.target.checked ? 'dark' : 'light');
                }}
              />
              Use dark mode
            </label>
            <Link href="/posts">
              <button style={{ padding: '10px' }}>Go to The Blog</button>
            </Link>
          </main>
        </RootLayout>
      </ThemeContext.Provider>
    </>
  );
}
