import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import RootLayout from './layout';
// import { Inter } from 'next/font/google';
import styles from '../styles/Main.module.css';
import { createContext, useContext, useState } from 'react';

const ThemeContext = createContext('light');
// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [theme, setTheme] = useState('light');

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeContext.Provider value={theme}>
        <RootLayout>
          {/* <main className={`${inter.className} ${styles.main}`}> */}
          <main className={styles.main}>
            <h1>Main page</h1>
            <Announcement />
            <label>
              <input
                type="checkbox"
                checked={theme === 'dark'}
                onChange={(e) => {
                  setTheme(e.target.checked ? 'dark' : 'light');
                }}
              />
              Use dark mode
            </label>
            <Link href="/posts">
              <button style={{ padding: '10px' }}>Go to The Blog</button>
            </Link>
          </main>
        </RootLayout>
      </ThemeContext.Provider>
    </>
  );
}
function Announcement() {
  const theme = useContext(ThemeContext);
  const className = 'container-' + theme;

  return (
    <article className={`${styles.container} ${styles[className]}`}>
      <Image
        src="/pet_game_general.png"
        alt="Bjanka greets you at this site."
        width={290}
        height={400}
      ></Image>
      <div className={styles.content}>
        <h2>Announcement</h2>
        <p>Here is our greatest news!</p>
        <p>Now we're offering tiny chikens.</p>
        <p>We're offering fluffy cats, too!</p>
      </div>
    </article>
  );
}
